version: "3.8"

volumes:
    finansist:

networks:
    finansistNet:

services:

    prometheus:
      image: prom/prometheus
      container_name: prometheus
      ports:
          - 9090:9090
      volumes:
          - ./Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      depends_on:
        - finansist    
      networks:
          - finansistNet

    grafana:
      image: grafana/grafana
      ports:
        - "3000:3000"
      container_name: grafana
      depends_on:
        - prometheus
      networks:
        - finansistNet


    finansist:
        build:
          context: .
          dockerfile: Dockerfile
        container_name: finansist
        ports:
          - 5000:80
